---
title: "newEVDeconv_7_11"
output: html_document
date: "2023-07-11"
---
# First Script Attempt

```{r}
library(readxl)
#exp<-read.csv("")
BiocManager::install("org.Hs.eg.db")
```
```{r}
library("org.Hs.eg.db")
library("tidyr")
serumDF<-read.csv("./totalRNA_EV_genes.csv", header = TRUE,check.names=FALSE,row.names=1)
serumDF<-t(apply(serumDF,1, function(x) tapply(x,colnames(serumDF),sum)))
#cleanSerumDF <- serumDF[,-1]
#rownames(cleanSerumDF) <- serumDF[,1]
#sigs.df<- as.data.frame(sigs.df)
#sigs.df$SYMBOL<-mapIds(org.Hs.eg.db,keys=rownames(sigs.df),keytype="ENSEMBL",column="SYMBOL")
#exp$ENSEMBL<-mapIds(org.Hs.eg.db,keys=rownames(serumDF),keytype="SYMBOL",column="ENSEMBL")

#apply(exp,1, function(x) tapply(x,colnames(exp),sum))

#exp<-replace(exp, is.na(exp), "NA")
ref.m<-read.csv("./refMatrix.csv", header = TRUE)
ref.m$SYMBOL<-mapIds(org.Hs.eg.db,keys=ref.m$Gene.id,keytype="ENSEMBL",column="SYMBOL") 

ref.m <- ref.m%>% drop_na()

cleanRef<- ref.m[,2:17]
rownames(cleanRef)<- ref.m$SYMBOL

cleanExp<-exp[2:13]
#cleanExp<-t(apply(cleanExp,1, function(x) tapply(x,colnames(cleanExp),sum)))
rownames(cleanExp)<-exp$X
```



```{r}
library(e1071)
### nu-SVR
### read the reference matrix as "ref.m"
x <- data.matrix(serumDF)
x <- (x - mean(x)) / sd(as.vector(x))
avdata.m <- x#the expression profile normalization
nu.v = c(0.25, 0.5, 0.75)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
do.exLR_origin <- function(avdata.m, ref.m, nu.v) {
  map.idx <- match(rownames(ref.m), rownames(avdata.m))
  rep.idx <- which(is.na(map.idx) == FALSE)
  data2.m <- avdata.m[map.idx[rep.idx], ]
  ref2.m <- ref.m[rep.idx, ]
  est.ab.lm <- list()
  est.lm <- list()
  nui <- 1
  for (nu in nu.v) {
    est.m <- matrix(NA, nrow = ncol(data2.m), ncol = ncol(ref2.m))
    colnames(est.m) <- colnames(ref2.m)
    rownames(est.m) <- colnames(data2.m)
    est.ab.m <- matrix(NA, nrow = ncol(data2.m), ncol = ncol(ref2.m))
    colnames(est.ab.m) <- colnames(ref2.m)
    rownames(est.ab.m) <- colnames(data2.m)
    
    for (s in seq_len(ncol(data2.m))) {
      svm.o <- svm(x = ref2.m, y = data2.m[, s], scale = TRUE, type = "nu-regression", kernel = "linear", nu = nu)
      coef.v <- t(svm.o$coefs) %*% svm.o$SV
      coef.v[which(coef.v < 0)] <- 1*10^-10
      est.ab.m[s,] <- coef.v
      total <- sum(coef.v)
      coef.v <- coef.v/total
      est.m[s, ] <- coef.v
    }
    est.lm[[nui]] <- est.m
    est.ab.lm[[nui]] <- est.ab.m
    nui <- nui + 1
  }
  
  #### select best nu using RMSE
  rmse.m <- matrix(NA, nrow = ncol(avdata.m), ncol = length(nu.v))
  for (nui in seq_along(nu.v)) {
    reconst.m <- ref2.m %*% t(est.lm[[nui]])
    s <- seq_len(ncol(avdata.m))
    rmse.m[s, nui] <- sqrt(colMeans((data2.m[, s] - reconst.m[, s])^2))
    message(nui)
  }
  colnames(rmse.m) <- nu.v
  nu.idx <- apply(rmse.m, 1, which.min)
  estF.m <- est.m
  for (s in seq_len(nrow(estF.m))) {
    estF.m[s, ] <- est.lm[[nu.idx[s]]][s, ]
  }
  estF.ab.m <- est.ab.m
  for (s in seq_len(nrow(estF.ab.m))) {
    estF.ab.m[s, ] <- est.ab.lm[[nu.idx[s]]][s, ]
  }
  #selecting min RMSE
  rmse.min.value <- as.data.frame(apply(rmse.m, 1, min))
  rownames(rmse.min.value) <- colnames(avdata.m)
  colnames(rmse.min.value)[1] <- 'RMSE'
  #caculating PCC
  pearson.corr.value <- c()
  for (i in 1:ncol(data2.m)) {
    cor.index <- cor.test(data2.m[, i], reconst.m[, i])
    cor.p <- as.numeric(cor.index$estimate)
    pearson.corr.value <- c(pearson.corr.value, cor.p)
  }
  estF.m <- cbind.data.frame(estF.m, pearson.corr.value, rmse.min.value)
  return(list(estF = estF.m, est.ab.sum = estF.ab.m, nu = nu.v[nu.idx]))
}
exLR_origin.results <- do.exLR_origin(as.matrix(avdata.m), as.matrix(cleanRef), nu.v)
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

```
```{r}
library(openxlsx)
write.xlsx(exLR_origin.results,"Output.xlsx")
```
##other stuff below

```{r setup, include=FALSE}

library(e1071)
library(parallel)
library(preprocessCore)

#Core algorithm of EV-origin
CoreAlg <- function(X, y, absolute, abs_method){
  
  #try different values of nu
  svn_itor <- 3
  
  res <- function(i){
    if(i==1){nus <- 0.25}
    if(i==2){nus <- 0.5}
    if(i==3){nus <- 0.75}
    model<-svm(X,y,type="nu-regression",kernel="linear",nu=nus,scale=F)
    model
  }
  
  if(Sys.info()['sysname'] == 'Windows') out <- mclapply(1:svn_itor, res, mc.cores=1) else
    out <- mclapply(1:svn_itor, res, mc.cores=svn_itor)
  
  nusvm <- rep(0,svn_itor)
  corrv <- rep(0,svn_itor)
  
  #do SVR
  t <- 1
  while(t <= svn_itor) {
    weights = t(out[[t]]$coefs) %*% out[[t]]$SV
    weights[which(weights<0)]<-0
    w<-weights/sum(weights)
    u <- sweep(X,MARGIN=2,w,'*')
    k <- apply(u, 1, sum)
    nusvm[t] <- sqrt((mean((k - y)^2)))
    corrv[t] <- cor(k, y)
    t <- t + 1
  }
  
  #pick best model
  rmses <- nusvm
  mn <- which.min(rmses)
  model <- out[[mn]]
  
  #get and normalize coefficients
  q <- t(model$coefs) %*% model$SV
  q[which(q<0)]<-0
  if(!absolute || abs_method == 'sig.score') w <- (q/sum(q)) #relative space (returns fractions)
  if(absolute && abs_method == 'no.sumto1') w <- q #absolute space (returns scores)
  
  mix_rmse <- rmses[mn]
  mix_r <- corrv[mn]
  
  newList <- list("w" = w, "mix_rmse" = mix_rmse, "mix_r" = mix_r)
  
}

#do Monte Carlo sampling and Pearson product-moment correlation R cadulation
doPerm <- function(perm, X, Y, absolute, abs_method){
  itor <- 1
  Ylist <- as.list(data.matrix(Y))
  dist <- matrix()
  
  while(itor <= perm){
    #print(itor)
    
    #random mixture
    yr <- as.numeric(Ylist[sample(length(Ylist),dim(X)[1])])
    
    #standardize mixture
    yr <- (yr - mean(yr)) / sd(yr)
    
    #run CIBERSORT core algorithm
    result <- CoreAlg(X, yr, absolute, abs_method)
    
    mix_r <- result$mix_r
    
    #store correlation
    if(itor == 1) {dist <- mix_r}
    else {dist <- rbind(dist, mix_r)}
    
    itor <- itor + 1
  }
  newList <- list("dist" = dist)
}

#main function
EV-origin <- function(sig_matrix, mixture_file, perm=0, QN=TRUE, absolute=FALSE, abs_method='sig.score'){
  
  if(absolute && abs_method != 'no.sumto1' && abs_method != 'sig.score') stop("abs_method must be set to either 'sig.score' or 'no.sumto1'")
  
  #read in data
  X <- read.table(sig_matrix,header=T,sep="\t",row.names=1,check.names=F)
  Y <- read.table(mixture_file, header=T, sep="\t",check.names=F)
  #to prevent crashing on duplicated gene symbols, add unique numbers to identical names
  dups <- dim(Y)[1] - length(unique(Y[,1]))
  if(dups > 0) {
    warning(paste(dups," duplicated gene symbol(s) found in mixture file!",sep=""))
    rownames(Y) <- make.names(Y[,1], unique=TRUE)
  }else {rownames(Y) <- Y[,1]}
  Y <- Y[,-1]
  
  X <- data.matrix(X)
  Y <- data.matrix(Y)
  
  #order
  X <- X[order(rownames(X)),]
  Y <- Y[order(rownames(Y)),]
  
  P <- perm #number of permutations
  
  #anti-log if max < 50 in mixture file
  #if(max(Y) < 50) {Y <- 2^Y}
  
  #quantile normalization of mixture file
  if(QN == TRUE){
    tmpc <- colnames(Y)
    tmpr <- rownames(Y)
    Y <- normalize.quantiles(Y)
    colnames(Y) <- tmpc
    rownames(Y) <- tmpr
  }
  
  #store original mixtures
  Yorig <- Y
  Ymedian <- max(median(Yorig),1)
  
  #intersect genes
  Xgns <- row.names(X)
  Ygns <- row.names(Y)
  YintX <- Ygns %in% Xgns
  Y <- Y[YintX,]
  XintY <- Xgns %in% row.names(Y)
  X <- X[XintY,]
  
  #standardize sig matrix
  X <- (X - mean(X)) / sd(as.vector(X))
  
  #empirical null distribution of correlation coefficients
  if(P > 0) {nulldist <- sort(doPerm(P, X, Y, absolute, abs_method)$dist)}
  
  header <- c('Mixture',colnames(X),"P-value","Correlation","RMSE")
  if(absolute) header <- c(header, paste('Absolute score (',abs_method,')',sep=""))
  
  output <- matrix()
  itor <- 1
  mixtures <- dim(Y)[2]
  pval <- 9999
  
  #iterate through mixtures
  while(itor <= mixtures){
    
    y <- Y[,itor]
    
    #standardize mixture
    y <- (y - mean(y)) / sd(y)
    
    #run SVR core algorithm
    result <- CoreAlg(X, y, absolute, abs_method)
    
    #get results
    w <- result$w
    mix_r <- result$mix_r
    mix_rmse <- result$mix_rmse
    
    if(absolute && abs_method == 'sig.score') {
      w <- w * median(Y[,itor]) / Ymedian
    }
    
    #calculate empirical p-value of R
    if(P > 0) {pval <- 1 - (which.min(abs(nulldist - mix_r)) / length(nulldist))}
    
    #print output
    out <- c(colnames(Y)[itor],w,pval,mix_r,mix_rmse)
    if(absolute) out <- c(out, sum(w))
    if(itor == 1) {output <- out}
    else {output <- rbind(output, out)}
    
    itor <- itor + 1
    
  }
  
  #save results
  write.table(rbind(header,output), file="EV-origin-Results.txt", sep="\t", row.names=F, col.names=F, quote=F)
  
  #return matrix object containing all results
  obj <- rbind(header,output)
  obj <- obj[,-1]
  obj <- obj[-1,]
  obj <- matrix(as.numeric(unlist(obj)),nrow=nrow(obj))
  rownames(obj) <- colnames(Y)
  if(!absolute){colnames(obj) <- c(colnames(X),"P-value","Correlation","RMSE")}
  else{colnames(obj) <- c(colnames(X),"P-value","Correlation","RMSE",paste('Absolute score (',abs_method,')',sep=""))}
  obj
}
```